version: "3.8"

services:
  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digidittos-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_APP_NAME: Digidittos CMS
      NEXT_PUBLIC_API_URL: http://localhost:5000/api/v1
    networks:
      - digidittos-frontend-network

networks:
  digidittos-frontend-network:
    driver: bridge
